from .semi_rotated_fcos_head import SemiRotatedFCOSHead
from .semi_rotated_fcos_head_mcl import SemiRotatedFCOSHeadMCL
from .semi_rotated_retina_head_mcl import SemiRotatedRetinaHeadMCL
from .semi_rotated_fcos_head_iou import SemiRotatedFCOSHeadIOU
from .soft_rotated_shared_2FC_bbox_head import SoftRotatedShared2FCBBoxHead

from .sparse_rotated_fcos_head import SparseRotatedFCOSHead
from .semi_rotated_fcos_head_v2 import SemiRotatedFCOSHeadV2
from .semi_rotated_fcos_head_v3 import SemiRotatedFCOSHeadV3